# Generated by Django 2.1 on 2018-08-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('DateTimeField', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('sent', models.BooleanField()),
                ('DateTimesent', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesttext', models.TextField()),
                ('DateTimeField', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('Messanger', models.CharField(default='viber', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('chatid', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('group', models.CharField(default='', max_length=20)),
                ('name', models.TextField()),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
    ]
